version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - rabbitmq
networks:
  rabbitmq:
    external:
      name: rabbitmq_network
